# Generated by Django 4.2.1 on 2023-05-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_deck', models.FileField(upload_to='original_decks/')),
                ('mobile_friendly_deck', models.FileField(blank=True, null=True, upload_to='mobile_decks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
