# Generated by Django 4.2.1 on 2023-05-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='named_entities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeck',
            name='noun_phrases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
