# Generated by Django 4.2.1 on 2023-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDC', '0002_pitchdeck_extracted_text_pitchdeck_named_entities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
