# Generated by Django 4.2.1 on 2023-05-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDC', '0003_pitchdeck_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchdeck',
            name='images',
        ),
        migrations.CreateModel(
            name='DeckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_images', to='MDC.pitchdeck')),
            ],
        ),
    ]
