# Generated by Django 4.2.1 on 2023-05-25 21:52

import MDC.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDC', '0004_remove_pitchdeck_images_deckimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckimage',
            name='image',
            field=models.ImageField(upload_to=MDC.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='pitchdeck',
            name='original_deck',
            field=models.FileField(upload_to=MDC.models.get_deck_upload_path),
        ),
    ]
